#!/usr/bin/env python3
"""
Script to generate corrected meals.json based on actual Moringa restaurant menu
"""
import json
from datetime import datetime

# Helper to create ingredient reference
def ing(ingredient_id, is_default=True, is_optional=False, extra_price=0.0):
    return {
        "ingredient_id": ingredient_id,
        "is_optional": is_optional,
        "is_default": is_default,
        "extra_price": extra_price
    }

# Ingredient IDs (from corrected_ingredients.json)
INGREDIENTS = {
    "avocado": "6b3c1bcc-823d-4e91-aeaf-9926b6689f25",
    "tuna": "7e6d477e-cf3c-41c5-81cc-181b54cbb298",
    "hard_egg": "4dc08412-3b0d-45a0-8b40-cc1125fb3668",
    "chicken": "cde134dd-4f1e-4526-bda3-6ccced66c0d5",
    "schnitzel": "e34739e2-41fa-4e7f-85c7-a19b7de6a2f2",
    "salmon": "ba452339-8822-4598-8f7e-f155fe78dfd2",
    "lettuce": "c0e40a67-5b2b-4990-aeb3-f81f27b0d246",
    "tomatoes": "8c5114b0-0a85-410e-a56f-d106da9b8ef1",
    "cucumber": "f1cb1f99-a159-4551-8f20-6b20a74e47a3",
    "onion": "8fb41a94-8445-48ea-9565-dc54c66119b1",
    "roasted_peppers": "6d85b598-d431-4104-a6e1-ec1a5d9e84b5",
    "sweet_potato": "2c925bb0-549c-4dcd-a4a5-a324a8c7cb5e",
    "eggplant_spread": "49271dd6-a4ac-40fa-81e6-4d9f4cbf6efa",
    "pesto_spread": "c8ba82e6-7d3c-472a-89a5-108d3dd5772e",
    "tahini": "0d36dcc4-ee72-40bb-9e8c-4447bfa2b599",
    "quinoa": "44df2f72-d660-4f28-bab6-8e3c73d119e7",
    "freekeh": "6a6fd6e8-b2b9-41fc-8968-9dc9980ab03d",
    "halloumi": "2ae679de-b3ca-4b54-ac59-d3f1bddff072",
    "artichoke": "8fcc04fc-dacf-4c58-b48a-9c80799baf9d",
    "beet": "da437a45-ab40-48da-bcfa-151961167363",
    "chard": "NEW-chard-001",
    "cherry_tomatoes": "NEW-cherry-tomatoes-001",
    "white_cabbage": "NEW-white-cabbage-001",
    "red_cabbage": "NEW-red-cabbage-001",
    "carrot": "NEW-carrot-001",
    "broccoli": "NEW-broccoli-001",
    "green_onion": "NEW-green-onion-001",
    "red_onion": "NEW-red-onion-001",
    "mint": "NEW-mint-001",
    "corn": "NEW-corn-001",
    "mushrooms": "NEW-mushrooms-001",
    "parsley": "NEW-parsley-001",
    "pickles": "NEW-pickles-001",
    "red_beans": "NEW-red-beans-001",
    "chickpeas": "NEW-chickpeas-001",
    "spaghetti": "NEW-spaghetti-001",
    "parmesan": "NEW-parmesan-001",
    "sundried_tomatoes": "NEW-sundried-tomatoes-001",
    "basil": "NEW-basil-001",
    "roasted_eggplant": "NEW-roasted-eggplant-001",
    "omelette": "NEW-omelette-001",
    "rice": "NEW-rice-001",
    "vegetables": "NEW-vegetables-001",
}

# Category IDs
CATEGORIES = {
    "sandwiches": "82f473ec-d7cb-483a-a6c6-4b7d3858eb30",
    "breakfast": "a619dcb2-7f51-4d3e-9c47-5a1183b9b1c8",
    "hot_drinks": "75ff270b-a59f-4a54-95e3-9196c719ebf7",
    "juices": "0ab8e5e9-8a37-49f7-ac84-5379642a9ae2",
    "main_courses": "d635197f-b779-400f-8e4d-864de3c3e90b",
    "salads": "23dec4fc-7a35-4d29-bfcb-eced14294865",
}

# Optional add-ons that can be added to salads (תוספות)
SALAD_ADDONS = [
    ing(INGREDIENTS["avocado"], is_default=False, is_optional=True, extra_price=5.0),
    ing(INGREDIENTS["tuna"], is_default=False, is_optional=True, extra_price=5.0),
    ing(INGREDIENTS["hard_egg"], is_default=False, is_optional=True, extra_price=5.0),
    ing(INGREDIENTS["chicken"], is_default=False, is_optional=True, extra_price=20.0),
    ing(INGREDIENTS["schnitzel"], is_default=False, is_optional=True, extra_price=20.0),
    ing(INGREDIENTS["salmon"], is_default=False, is_optional=True, extra_price=25.0),
]

meals = [
    # ==================== SANDWICHES (כריכים) ====================
    {
        "_id": "573bfa5e-a830-476b-8496-88a095a062c3",
        "name": {"en": "Vegan Sandwich", "ar": "ساندويتش نباتي", "he": "כריך טבעוני"},
        "description": {
            "en": "Pesto spread, eggplant spread, roasted eggplant, sweet potato, roasted peppers and avocado",
            "ar": "صلصة بيستو، معجون باذنجان، باذنجان مشوي، بطاطا حلوة، فلفل مشوي وأفوكادو",
            "he": "ממרח פסטו, ממרח חציל, חציל קלוי, בטטה, פלפלים קלויים ואבוקדו"
        },
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [
            ing(INGREDIENTS["pesto_spread"]),
            ing(INGREDIENTS["eggplant_spread"]),
            ing(INGREDIENTS["roasted_eggplant"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["roasted_peppers"]),
            ing(INGREDIENTS["avocado"]),
        ],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "2958e8f9-a5b5-4e30-b009-1c313c93c513",
        "name": {"en": "Tuna Sandwich", "ar": "ساندويتش تونة", "he": "כריך טונה"},
        "description": {
            "en": "Eggplant or avocado spread, tuna, roasted peppers and whole tahini with salt and lemon seasoning",
            "ar": "معجون باذنجان أو أفوكادو، تونة، فلفل مشوي وطحينة كاملة مع ملح وليمون",
            "he": "ממרח חציל או אבוקדו, טונה, פלפלים קלויים וטחינה מלאה בתיבול מלח לימון"
        },
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [
            ing(INGREDIENTS["eggplant_spread"]),
            ing(INGREDIENTS["tuna"]),
            ing(INGREDIENTS["roasted_peppers"]),
            ing(INGREDIENTS["tahini"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "960bdb1e-d1f8-4108-9c49-4a5a32909034",
        "name": {"en": "Omelette Sandwich", "ar": "ساندويتش عجة", "he": "כריך חביתה"},
        "description": {"en": "Omelette", "ar": "عجة", "he": "חביתה"},
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [ing(INGREDIENTS["omelette"])],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "6b41eaaa-2615-48c1-9b92-5b183de7e245",
        "name": {"en": "Hard Boiled Egg Sandwich", "ar": "ساندويتش بيضة مسلوقة", "he": "כריך ביצה קשה"},
        "description": {"en": "Hard boiled egg and avocado", "ar": "بيضة مسلوقة وأفوكادو", "he": "ביצה קשה ואבוקדו"},
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [
            ing(INGREDIENTS["hard_egg"]),
            ing(INGREDIENTS["avocado"]),
        ],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "2a64ad6d-6e37-47d8-943c-757e59c3b6f6",
        "name": {"en": "Cheese Sandwich", "ar": "ساندويتش جبن", "he": "כריך גבינות"},
        "description": {
            "en": "Three types of cheese: garlic cream, vegetable cream and Bulgarian cheese",
            "ar": "ثلاثة أنواع من الجبن: كريمة ثوم، كريمة خضار وجبنة بلغارية",
            "he": "שלושה סוגי גבינות בכריך: שמנת שום שמיר, שמנת ירקות ובולגרית"
        },
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1553909489-cd47e0907980",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "c2a93d7b-4cdc-4276-b040-e8daa9db228d",
        "name": {"en": "Avocado Sandwich", "ar": "ساندويتش أفوكادو", "he": "כריך אבוקדו"},
        "description": {"en": "Avocado sandwich", "ar": "ساندويتش أفوكادو", "he": "כריך אבוקדו"},
        "price": 30.0,
        "image": "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [ing(INGREDIENTS["avocado"])],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "cf8c25aa-ed33-4dee-97a9-796c5b8fdd4e",
        "name": {"en": "Chicken Sandwich", "ar": "ساندويتش دجاج", "he": "כריך עוף"},
        "description": {
            "en": "Eggplant spread, roasted peppers, sweet potato, lettuce, tomatoes, cucumber",
            "ar": "معجون باذنجان، فلفل مشوي، بطاطا حلوة، خس، طماطم، خيار",
            "he": "ממרח חציל, פלפלים קלויים, בטטה, חסה, עגבניות, מלפפון"
        },
        "price": 40.0,
        "image": "https://images.unsplash.com/photo-1606755962773-d324e0a13086",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [
            ing(INGREDIENTS["chicken"]),
            ing(INGREDIENTS["eggplant_spread"]),
            ing(INGREDIENTS["roasted_peppers"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["tomatoes"]),
            ing(INGREDIENTS["cucumber"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "342031d3-61a4-4821-8fac-3769239dd28d",
        "name": {"en": "Schnitzel Sandwich", "ar": "ساندويتش شنيتسل", "he": "כריך שניצל"},
        "description": {
            "en": "Pesto spread, lettuce, tomatoes, cucumber, sweet potato, roasted peppers",
            "ar": "صلصة بيستو، خس، طماطم، خيار، بطاطا حلوة، فلفل مشوي",
            "he": "ממרח פסטו, חסה, עגבניות, מלפפון, בטטה, פלפלים קלויים"
        },
        "price": 40.0,
        "image": "https://images.unsplash.com/photo-1619894991209-e2aa59f7e4fc",
        "category_id": CATEGORIES["sandwiches"],
        "ingredients": [
            ing(INGREDIENTS["schnitzel"]),
            ing(INGREDIENTS["pesto_spread"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["tomatoes"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["roasted_peppers"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },

    # ==================== BREAKFAST (ארוחת בוקר) ====================
    {
        "_id": "ae599b22-19fc-4c67-8275-ed7e0b465c7c",
        "name": {"en": "Shakshuka", "ar": "شكشوكة", "he": "שקשוקה"},
        "description": {
            "en": "Shakshuka with personal salad and cheese & dips set",
            "ar": "شكشوكة مع سلطة شخصية وطبق جبن ومغموسات",
            "he": "שקשוקה בתוספת סלט אישי וסט גבינות ומטבלים"
        },
        "price": 65.0,
        "image": "https://images.unsplash.com/photo-1587593810167-a84920ea0781",
        "category_id": CATEGORIES["breakfast"],
        "ingredients": [],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "5614c0af-c234-40b2-9eb8-848d9d109a28",
        "name": {"en": "Vegetable Omelette", "ar": "عجة خضار", "he": "חביתה ירק"},
        "description": {
            "en": "Your choice of eggs, with personal salad or vegetables",
            "ar": "بيض حسب اختيارك، مع سلطة شخصية أو خضروات",
            "he": "ביצים לבחירתך, תוספת סלט אישי או ירקות"
        },
        "price": 45.0,
        "image": "https://images.unsplash.com/photo-1608039755401-742074f0548d",
        "category_id": CATEGORIES["breakfast"],
        "ingredients": [ing(INGREDIENTS["omelette"])],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "c28e0ec7-7a7e-4fe1-8e75-0d1981f5e198",
        "name": {"en": "Cheese Toast", "ar": "توست جبن", "he": "טוסט גבינה"},
        "description": {
            "en": "Gouda cheese toast with pesto",
            "ar": "توست جبنة جودا مع بيستو",
            "he": "טוסט גבינה גאודה עם פסטו"
        },
        "price": 40.0,
        "image": "https://images.unsplash.com/photo-1528736235302-52922df5c122",
        "category_id": CATEGORIES["breakfast"],
        "ingredients": [ing(INGREDIENTS["pesto_spread"])],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "a579b209-d3d5-4026-a554-2823776cfec5",
        "name": {"en": "Pastrami Toast", "ar": "توست باسترامي", "he": "טוסט פסטרמה"},
        "description": {
            "en": "Pepper beef pastrami toast + cheese pesto and your choice of vegetables",
            "ar": "توست باسترامي لحم فلفل + جبنة بيستو وخضروات حسب اختيارك",
            "he": "טוסט פסטרמה בקר פלפל + גבינה פסטו וירקות לבחירתך"
        },
        "price": 40.0,
        "image": "https://images.unsplash.com/photo-1590759668628-05b0fc34b304",
        "category_id": CATEGORIES["breakfast"],
        "ingredients": [ing(INGREDIENTS["pesto_spread"])],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-custom-toast-001",
        "name": {"en": "Custom Toast", "ar": "توست مخصص", "he": "טוסט בהרכבה עצמית"},
        "description": {
            "en": "Build your own toast",
            "ar": "قم ببناء التوست الخاص بك",
            "he": "טוסט בהרכבה עצמית"
        },
        "price": 40.0,
        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8",
        "category_id": CATEGORIES["breakfast"],
        "ingredients": [],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },

    # ==================== HOT DRINKS (שתיה חמה) ====================
    {
        "_id": "d5517e85-9de4-4956-88ec-22046288be2c",
        "name": {"en": "Latte", "ar": "لاتيه", "he": "קפה הפוך"},
        "description": {"en": "Latte", "ar": "لاتيه", "he": "קפה הפוך"},
        "price": 10.0,
        "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "d5015e53-eb91-4a2e-84b3-774dc7bec3e3",
        "name": {"en": "Soy Latte", "ar": "لاتيه صويا", "he": "קפה הפוך סויה"},
        "description": {"en": "Latte with soy milk", "ar": "لاتيه مع حليب الصويا", "he": "קפה הפוך עם חלב סויה"},
        "price": 13.0,
        "image": "https://images.unsplash.com/photo-1572442388796-11668a67e53d",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "f6c14866-f381-4704-84d3-17f7becced5b",
        "name": {"en": "Oat Latte", "ar": "لاتيه شوفان", "he": "קפה הפוך שיבולת שועל"},
        "description": {"en": "Latte with oat milk", "ar": "لاتيه مع حليب الشوفان", "he": "קפה הפוך עם חלב שיבולת שועל"},
        "price": 13.0,
        "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-almond-latte-001",
        "name": {"en": "Almond Latte", "ar": "لاتيه لوز", "he": "הפוך שקדים"},
        "description": {"en": "Latte with almond milk", "ar": "لاتيه مع حليب اللوز", "he": "הפוך שקדים"},
        "price": 13.0,
        "image": "https://images.unsplash.com/photo-1545665225-b23b99e4d45e",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "04517bac-d3dc-472d-88b5-79e0d0ec5f31",
        "name": {"en": "Espresso", "ar": "إسبريسو", "he": "אספרסו"},
        "description": {"en": "Espresso short | long", "ar": "إسبريسو قصير | طويل", "he": "אספרסו קצר | ארוך"},
        "price": 10.0,
        "image": "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "6b86829f-d9c1-47dd-bdf7-e1d89d26d156",
        "name": {"en": "Americano", "ar": "أمريكانو", "he": "אמריקנו"},
        "description": {"en": "Americano", "ar": "أمريكانو", "he": "אמריקנו"},
        "price": 10.0,
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_popular": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "f33c0a77-18c3-4519-aed1-7ac06f5ba502",
        "name": {"en": "Tea", "ar": "شاي", "he": "תה"},
        "description": {"en": "Tea", "ar": "شاي", "he": "תה"},
        "price": 10.0,
        "image": "https://images.unsplash.com/photo-1556679343-c7306c1976bc",
        "category_id": CATEGORIES["hot_drinks"],
        "ingredients": [],
        "preparation_time": 5,
        "is_active": True,
        "is_available": True,
    },

    # ==================== FRESH JUICES (מיץ טבעי) ====================
    {
        "_id": "a5b6b41f-58ed-439b-93b6-ba0879ee4d77",
        "name": {"en": "Green Juice", "ar": "عصير أخضر", "he": "מיץ ירוק"},
        "description": {
            "en": "Cucumber, green apple, celery, mint",
            "ar": "خيار، تفاح أخضر، كرفس، نعناع",
            "he": "מלפפון, תפוח ירוק, סלרי, נענע"
        },
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1610970881699-44a5587cabec",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-beet-juice-001",
        "name": {"en": "Beet Juice", "ar": "عصير شمندر", "he": "סלק"},
        "description": {"en": "Beet", "ar": "شمندر", "he": "סלק"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1567012290133-ecdb8f34e1c3",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-carrot-juice-001",
        "name": {"en": "Carrot Juice", "ar": "عصير جزر", "he": "גזר"},
        "description": {"en": "Carrot", "ar": "جزر", "he": "גזר"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1556911220-bff31c812dba",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-orange-juice-001",
        "name": {"en": "Orange Juice", "ar": "عصير برتقال", "he": "תפוזים"},
        "description": {"en": "Oranges", "ar": "برتقال", "he": "תפוזים"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1600271886742-f049cd451bba",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-beet-carrot-juice-001",
        "name": {"en": "Beet & Carrot Juice", "ar": "عصير شمندر وجزر", "he": "סלק וגזר"},
        "description": {"en": "Beet, carrot", "ar": "شمندر، جزر", "he": "סלק, גזר"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1610970881699-44a5587cabec",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-carrot-orange-juice-001",
        "name": {"en": "Carrot & Orange Juice", "ar": "عصير جزر وبرتقال", "he": "גזר ותפוזים"},
        "description": {"en": "Carrot, oranges", "ar": "جزر، برتقال", "he": "גזר, תפוזים"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1622597467836-f3c7ca9d2f0c",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-orange-beet-juice-001",
        "name": {"en": "Orange & Beet Juice", "ar": "عصير برتقال وشمندر", "he": "תפוזים וסלק"},
        "description": {"en": "Oranges, beet", "ar": "برتقال، شمندر", "he": "תפוזים, סלק"},
        "price": 23.0,
        "image": "https://images.unsplash.com/photo-1600271886742-f049cd451bba",
        "category_id": CATEGORIES["juices"],
        "ingredients": [],
        "preparation_time": 10,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },

    # ==================== MAIN COURSES (עיקריות) ====================
    {
        "_id": "NEW-chicken-rice-001",
        "name": {"en": "Chicken Breast with Rice", "ar": "صدر دجاج مع أرز", "he": "חזה עוף עם אורז"},
        "description": {
            "en": "Chicken breast with rice and vegetables",
            "ar": "صدر دجاج مع أرز وخضروات",
            "he": "חזה עוף עם אורז וירקות"
        },
        "price": 65.0,
        "image": "https://images.unsplash.com/photo-1598103442097-8b74394b95c6",
        "category_id": CATEGORIES["main_courses"],
        "ingredients": [
            ing(INGREDIENTS["chicken"]),
            ing(INGREDIENTS["rice"]),
            ing(INGREDIENTS["vegetables"]),
        ],
        "preparation_time": 25,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-salmon-rice-001",
        "name": {"en": "Salmon with Rice", "ar": "سلمون مع أرز", "he": "סלמון עם אורז"},
        "description": {
            "en": "Baked salmon with rice and vegetables",
            "ar": "سلمون مشوي مع أرز وخضروات",
            "he": "סלמון אפוי עם אורז וירקות"
        },
        "price": 85.0,
        "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
        "category_id": CATEGORIES["main_courses"],
        "ingredients": [
            ing(INGREDIENTS["salmon"]),
            ing(INGREDIENTS["rice"]),
            ing(INGREDIENTS["vegetables"]),
        ],
        "preparation_time": 25,
        "is_active": True,
        "is_available": True,
    },

    # ==================== SALADS (סלטים) ====================
    {
        "_id": "NEW-quinoa-salad-001",
        "name": {"en": "Quinoa Salad", "ar": "سلطة كينوا", "he": "סלט קינואה"},
        "description": {
            "en": "Lettuce, cucumber, sweet potato, beet, red onion, quinoa",
            "ar": "خس، خيار، بطاطا حلوة، شمندر، بصل أحمر، كينوا",
            "he": "חסה, מלפפון, בטטה, סלק, בצל סגול, קינואה"
        },
        "price": 45.0,
        "image": "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["beet"]),
            ing(INGREDIENTS["red_onion"]),
            ing(INGREDIENTS["quinoa"]),
        ] + SALAD_ADDONS,
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-freekeh-salad-001",
        "name": {"en": "Freekeh Salad", "ar": "سلطة فريكة", "he": "סלט פריקה"},
        "description": {
            "en": "Lettuce, green onion, mint, cherry tomatoes, chickpeas, freekeh",
            "ar": "خس، بصل أخضر، نعناع، طماطم كرزية، حمص، فريكة",
            "he": "חסה, בצל ירוק, נענע, שירי צבעים, חומוס גרגרים, פריקה"
        },
        "price": 45.0,
        "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["green_onion"]),
            ing(INGREDIENTS["mint"]),
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["chickpeas"]),
            ing(INGREDIENTS["freekeh"]),
        ] + SALAD_ADDONS,
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-spaghetti-salad-001",
        "name": {"en": "Spaghetti Salad", "ar": "سلطة سباغيتي", "he": "סלט ספגטי"},
        "description": {
            "en": "Lettuce, cucumber, cherry tomatoes, carrot, white cabbage, red cabbage, corn, red onion, mushrooms, spaghetti, pesto sauce, parmesan cheese",
            "ar": "خس، خيار، طماطم كرزية، جزر، كرنب أبيض، كرنب أحمر، ذرة، بصل أحمر، فطر، سباغيتي، صلصة بيستو، جبنة بارميزان",
            "he": "חסה, מלפפון, שירי, גזר, כרוב לבן, כרוב אדום, גמבה, בצל סגול, פטריות, ספגטי, רוטב פסטו, גבינת פרמיז'ן"
        },
        "price": 50.0,
        "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["white_cabbage"]),
            ing(INGREDIENTS["red_cabbage"]),
            ing(INGREDIENTS["corn"]),
            ing(INGREDIENTS["red_onion"]),
            ing(INGREDIENTS["mushrooms"]),
            ing(INGREDIENTS["spaghetti"]),
            ing(INGREDIENTS["pesto_spread"]),
            ing(INGREDIENTS["parmesan"]),
        ] + SALAD_ADDONS,
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-halloumi-salad-001",
        "name": {"en": "Halloumi Salad", "ar": "سلطة حلومي", "he": "סלט חלומי"},
        "description": {
            "en": "Lettuce, cucumber, cherry tomatoes, red onion, mushrooms, sweet potato, halloumi cheese",
            "ar": "خس، خيار، طماطم كرزية، بصل أحمر، فطر، بطاطا حلوة، جبنة حلومي",
            "he": "חסה, מלפפון, שירי, בצל סגול, פטריות, בטטה, גבינת חלומי"
        },
        "price": 55.0,
        "image": "https://images.unsplash.com/photo-1546793665-c74683f339c1",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["red_onion"]),
            ing(INGREDIENTS["mushrooms"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["halloumi"]),
        ] + SALAD_ADDONS,
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-artichoke-salad-001",
        "name": {"en": "Artichoke Salad", "ar": "سلطة أرضي شوكي", "he": "סלט ארטישוק"},
        "description": {
            "en": "Cherry tomatoes, red onion, artichoke, sun-dried tomatoes, basil",
            "ar": "طماطم كرزية، بصل أحمر، أرضي شوكي، طماطم مجففة، ريحان",
            "he": "שירי, בצל סגול, ארטישוק, עגבניות מיובשות, בזיליקום"
        },
        "price": 50.0,
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["red_onion"]),
            ing(INGREDIENTS["artichoke"]),
            ing(INGREDIENTS["sundried_tomatoes"]),
            ing(INGREDIENTS["basil"]),
        ] + SALAD_ADDONS,
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-tuna-salad-001",
        "name": {"en": "Tuna Salad", "ar": "سلطة تونة", "he": "סלט טונה"},
        "description": {
            "en": "Lettuce, white/red cabbage, red onion, mushrooms, carrot, parsley, pickles, corn",
            "ar": "خس، كرنب أبيض/أحمر، بصل أحمر، فطر، جزر، بقدونس، مخلل، ذرة",
            "he": "חסה, כרוב לבן/אדום, בצל אדום, פטריות, גזר, פטרוזליה, מלפפון חמוץ, גמבה"
        },
        "price": 49.0,
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["tuna"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["white_cabbage"]),
            ing(INGREDIENTS["red_cabbage"]),
            ing(INGREDIENTS["red_onion"]),
            ing(INGREDIENTS["mushrooms"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["parsley"]),
            ing(INGREDIENTS["pickles"]),
            ing(INGREDIENTS["corn"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-egg-salad-001",
        "name": {"en": "Hard Boiled Egg Salad", "ar": "سلطة بيضة مسلوقة", "he": "סלט ביצה קשה"},
        "description": {
            "en": "Lettuce, chard, cucumber, carrot, white/red cabbage, broccoli, mushrooms, mint, sweet potato",
            "ar": "خس، سلق، خيار، جزر، كرنب أبيض/أحمر، بروكلي، فطر، نعناع، بطاطا حلوة",
            "he": "חסה, טרד, מלפפון, גזר, כרוב לבן/אדום, ברוקלי, פטריות, נענע, בטטה"
        },
        "price": 49.0,
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["hard_egg"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["chard"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["white_cabbage"]),
            ing(INGREDIENTS["red_cabbage"]),
            ing(INGREDIENTS["broccoli"]),
            ing(INGREDIENTS["mushrooms"]),
            ing(INGREDIENTS["mint"]),
            ing(INGREDIENTS["sweet_potato"]),
        ],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-avocado-salad-001",
        "name": {"en": "Avocado Salad", "ar": "سلطة أفوكادو", "he": "סלט אבוקדו"},
        "description": {
            "en": "Lettuce, chard, cucumber, cherry tomatoes, carrot, sweet potato, beet, broccoli, red beans",
            "ar": "خس، سلق، خيار، طماطم كرزية، جزر، بطاطا حلوة، شمندر، بروكلي، فاصوليا حمراء",
            "he": "חסה, טרד, מלפפון, שירי צבעים, גזר, בטטה, סלק, ברוקלי, שעועית אדומה"
        },
        "price": 49.0,
        "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["avocado"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["chard"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["beet"]),
            ing(INGREDIENTS["broccoli"]),
            ing(INGREDIENTS["red_beans"]),
        ],
        "preparation_time": 15,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-chicken-salad-001",
        "name": {"en": "Chicken Salad", "ar": "سلطة دجاج", "he": "סלט עוף"},
        "description": {
            "en": "Lettuce, cherry tomatoes, cucumber, carrot, white/red cabbage, mushrooms, red onion",
            "ar": "خس، طماطم كرزية، خيار، جزر، كرنب أبيض/أحمر، فطر، بصل أحمر",
            "he": "חסה, שירי צבעים, מלפפון, גזר, כרוב לבן אדום, פטריות, בצל סגול"
        },
        "price": 57.0,
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["chicken"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["cherry_tomatoes"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["white_cabbage"]),
            ing(INGREDIENTS["red_cabbage"]),
            ing(INGREDIENTS["mushrooms"]),
            ing(INGREDIENTS["red_onion"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
    {
        "_id": "NEW-salmon-salad-001",
        "name": {"en": "Salmon Salad", "ar": "سلطة سلمون", "he": "סלט סלמון"},
        "description": {
            "en": "Lettuce, cucumber, carrot, white/red cabbage, sweet potato, broccoli, green onion",
            "ar": "خس، خيار، جزر، كرنب أبيض/أحمر، بطاطا حلوة، بروكلي، بصل أخضر",
            "he": "חסה, מלפפון, גזר, כרוב לבן אדום, בטטה, ברוקלי, בצל ירוק"
        },
        "price": 65.0,
        "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
        "category_id": CATEGORIES["salads"],
        "ingredients": [
            ing(INGREDIENTS["salmon"]),
            ing(INGREDIENTS["lettuce"]),
            ing(INGREDIENTS["cucumber"]),
            ing(INGREDIENTS["carrot"]),
            ing(INGREDIENTS["white_cabbage"]),
            ing(INGREDIENTS["red_cabbage"]),
            ing(INGREDIENTS["sweet_potato"]),
            ing(INGREDIENTS["broccoli"]),
            ing(INGREDIENTS["green_onion"]),
        ],
        "preparation_time": 15,
        "is_active": True,
        "is_available": True,
    },
]

# Write to JSON file
output_file = "e:/Moringa/backend/data/corrected_meals.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(meals, f, ensure_ascii=False, indent=2)

print(f"✅ Created {len(meals)} meals in {output_file}")
print(f"\nBreakdown:")
print(f"  - Sandwiches: 8 meals")
print(f"  - Breakfast: 5 meals")
print(f"  - Hot Drinks: 7 meals")
print(f"  - Fresh Juices: 7 meals")
print(f"  - Main Courses: 2 meals")
print(f"  - Salads: 11 meals (with optional add-ons)")
